# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]
plugins             : [jekyll-paginate]

# Permalinks
permalink           : pretty

# Setup
title               : I'm Just A Programmer
tagline             : ''
description         : ''
baseurl             : /

author              : Nick Yang
name                : 'Nick Yang'
# url                 : https://nick10811.github.io/
url                 : /

paginate            : 10

# Custom vars
version             : 0.1.0
linkedin_username   : nick10811
github_username     : nick10811
twitter_username    : nick10811_
