name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main 
      
jobs:
  github_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build
        uses: jerryjvl/jekyll-build-action@v1

      - name: Update tags
        shell: bash
        run: |
          rm -rf tags/
          cp -R _site/tags .
      
      - name: Commit tags
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: 'Update tags'
            commit_options: '--no-verify'
            commit_user_name: ${{ github.actor }}
            commit_user_email: ${{ github.actor }}@users.noreply.github.com
            commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            file_pattern: 'tags/'
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/
